In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('fifa21_raw_data.csv')

/var/folders/dr/05g6dmcd47v9mvnt25smv94h0000gn/T/ipykernel_87348/3983473707.py:1: DtypeWarning: Columns (76) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv('fifa21_raw_data.csv')

In [3]:
df.head()

,ID,Name,LongName,photoUrl,playerUrl,Nationality,Age,↓OVA,POT,Club,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,158023,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,33,93,93,\n\n\n\nFC Barcelona,...,Medium,Low,5 ★,85,92,91,95,38,65,771
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,35,92,92,\n\n\n\nJuventus,...,High,Low,5 ★,89,93,81,89,35,77,562
2,200389,J. Oblak,Jan Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,27,91,93,\n\n\n\nAtlético Madrid,...,Medium,Medium,3 ★,87,92,78,90,52,90,150
3,192985,K. De Bruyne,Kevin De Bruyne,https://cdn.sofifa.com/players/192/985/21_60.png,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,29,91,91,\n\n\n\nManchester City,...,High,High,4 ★,76,86,93,88,64,78,207
4,190871,Neymar Jr,Neymar da Silva Santos Jr.,https://cdn.sofifa.com/players/190/871/21_60.png,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,28,91,91,\n\n\n\nParis Saint-Germain,...,High,Medium,5 ★,91,85,86,94,36,59,595

In [4]:
df.shape

(18979, 77)

In [5]:
df.describe()

,ID,Age,↓OVA,POT,BOV,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,...,GK Positioning,GK Reflexes,Total Stats,Base Stats,PAC,SHO,PAS,DRI,DEF,PHY
count,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,...,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000
mean,226403.384794,25.194109,65.718636,71.136414,66.751726,248.938142,49.688392,45.842405,51.942726,58.768112,...,16.217187,16.519627,1595.286949,355.702197,67.453975,53.457031,57.681016,62.875020,49.866221,64.368934
std,27141.054157,4.710520,6.968999,6.114635,6.747193,74.299428,18.131153,19.567081,17.294409,14.519106,...,17.002239,17.854079,269.874789,40.761117,10.677859,13.827425,10.081857,9.927415,16.443213,9.601883
min,41.000000,16.000000,47.000000,47.000000,48.000000,42.000000,6.000000,3.000000,5.000000,7.000000,...,2.000000,2.000000,747.000000,232.000000,25.000000,16.000000,25.000000,25.000000,12.000000,28.000000
25%,210135.000000,21.000000,61.000000,67.000000,62.000000,222.000000,38.000000,30.000000,44.000000,54.000000,...,8.000000,8.000000,1452.000000,327.000000,61.000000,44.000000,51.000000,57.000000,35.000000,58.000000
50%,232418.000000,25.000000,66.000000,71.000000,67.000000,263.000000,54.000000,49.000000,55.000000,62.000000,...,11.000000,11.000000,1627.000000,356.000000,68.000000,56.000000,58.000000,64.000000,53.000000,65.000000
75%,246922.500000,29.000000,70.000000,75.000000,71.000000,297.000000,63.000000,62.000000,64.000000,68.000000,...,14.000000,14.000000,1781.000000,384.000000,75.000000,64.000000,64.000000,69.000000,63.000000,71.000000
max,259216.000000,53.000000,93.000000,95.000000,93.000000,437.000000,94.000000,95.000000,93.000000,94.000000,...,91.000000,90.000000,2316.000000,498.000000,96.000000,93.000000,93.000000,95.000000,91.000000,91.000000

In [6]:
df.info

<bound method DataFrame.info of            ID               Name                      LongName  \
0      158023           L. Messi                  Lionel Messi
1       20801  Cristiano Ronaldo  C. Ronaldo dos Santos Aveiro
2      200389           J. Oblak                     Jan Oblak
3      192985       K. De Bruyne               Kevin De Bruyne
4      190871          Neymar Jr    Neymar da Silva Santos Jr.
...       ...                ...                           ...
18974  247223             Xia Ao                        Ao Xia
18975  258760           B. Hough                     Ben Hough
18976  252757        R. McKinley                Ronan McKinley
18977  243790       Wang Zhen'ao                  Zhen'ao Wang
18978  252520          Zhou Xiao                     Xiao Zhou

                                               photoUrl  \
0      https://cdn.sofifa.com/players/158/023/21_60.png
1      https://cdn.sofifa.com/players/020/801/21_60.png
2      https://cdn.sofifa.com/players/200/389/21_60.png
3      https://cdn.sofifa.com/players/192/985/21_60.png
4      https://cdn.sofifa.com/players/190/871/21_60.png
...                                                 ...
18974  https://cdn.sofifa.com/players/247/223/21_60.png
18975  https://cdn.sofifa.com/players/258/760/21_60.png
18976  https://cdn.sofifa.com/players/252/757/21_60.png
18977  https://cdn.sofifa.com/players/243/790/21_60.png
18978  https://cdn.sofifa.com/players/252/520/21_60.png

                                               playerUrl Nationality  Age  \
0      http://sofifa.com/player/158023/lionel-messi/2...   Argentina   33
1      http://sofifa.com/player/20801/c-ronaldo-dos-s...    Portugal   35
2      http://sofifa.com/player/200389/jan-oblak/210006/    Slovenia   27
3      http://sofifa.com/player/192985/kevin-de-bruyn...     Belgium   29
4      http://sofifa.com/player/190871/neymar-da-silv...      Brazil   28
...                                                  ...         ...  ...
18974     http://sofifa.com/player/247223/ao-xia/210006/    China PR   21
18975  http://sofifa.com/player/258760/ben-hough/210006/     England   17
18976  http://sofifa.com/player/252757/ronan-mckinley...     England   18
18977  http://sofifa.com/player/243790/zhenao-wang/21...    China PR   20
18978  http://sofifa.com/player/252520/xiao-zhou/210006/    China PR   21

       ↓OVA  POT                         Club  ...     A/W     D/W   IR PAC  \
0        93   93         \n\n\n\nFC Barcelona  ...  Medium     Low  5 ★  85
1        92   92             \n\n\n\nJuventus  ...    High     Low  5 ★  89
2        91   93      \n\n\n\nAtlético Madrid  ...  Medium  Medium  3 ★  87
3        91   91      \n\n\n\nManchester City  ...    High    High  4 ★  76
4        91   91  \n\n\n\nParis Saint-Germain  ...    High  Medium  5 ★  91
...     ...  ...                          ...  ...     ...     ...  ...  ..
18974    47   55           \n\n\n\nWuhan Zall  ...  Medium  Medium  1 ★  64
18975    47   67      \n\n\n\nOldham Athletic  ...  Medium  Medium  1 ★  64
18976    47   65           \n\n\n\nDerry City  ...  Medium  Medium  1 ★  63
18977    47   57     \n\n\n\nDalian YiFang FC  ...  Medium  Medium  1 ★  58
18978    47   57     \n\n\n\nDalian YiFang FC  ...  Medium  Medium  1 ★  62

      SHO  PAS DRI DEF PHY Hits
0      92   91  95  38  65  771
1      93   81  89  35  77  562
2      92   78  90  52  90  150
3      86   93  88  64  78  207
4      85   86  94  36  59  595
...    ..  ...  ..  ..  ..  ...
18974  28   26  38  48  51  NaN
18975  40   48  49  35  45  NaN
18976  39   44  46  40  53  NaN
18977  49   41  49  30  44  NaN
18978  22   39  42  45  55  NaN

[18979 rows x 77 columns]>

In [7]:
df.isnull().sum()

ID              0
Name            0
LongName        0
photoUrl        0
playerUrl       0
             ...
PAS             0
DRI             0
DEF             0
PHY             0
Hits         2595
Length: 77, dtype: int64

In [8]:
df.drop(columns=['Name','photoUrl','playerUrl'],axis=1,inplace=True)

In [9]:
df.rename(columns={'LongName':'Name'},inplace=True)

In [10]:
df.head()

,ID,Name,Nationality,Age,↓OVA,POT,Club,Contract,Positions,Height,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,158023,Lionel Messi,Argentina,33,93,93,\n\n\n\nFC Barcelona,2004 ~ 2021,"RW, ST, CF",170cm,...,Medium,Low,5 ★,85,92,91,95,38,65,771
1,20801,C. Ronaldo dos Santos Aveiro,Portugal,35,92,92,\n\n\n\nJuventus,2018 ~ 2022,"ST, LW",187cm,...,High,Low,5 ★,89,93,81,89,35,77,562
2,200389,Jan Oblak,Slovenia,27,91,93,\n\n\n\nAtlético Madrid,2014 ~ 2023,GK,188cm,...,Medium,Medium,3 ★,87,92,78,90,52,90,150
3,192985,Kevin De Bruyne,Belgium,29,91,91,\n\n\n\nManchester City,2015 ~ 2023,"CAM, CM",181cm,...,High,High,4 ★,76,86,93,88,64,78,207
4,190871,Neymar da Silva Santos Jr.,Brazil,28,91,91,\n\n\n\nParis Saint-Germain,2017 ~ 2022,"LW, CAM",175cm,...,High,Medium,5 ★,91,85,86,94,36,59,595

In [11]:
df['Height'].str.endswith('cm').all()

False

In [12]:
df['Height'][~df['Height'].str.endswith('cm')]

793     6'2"
847     6'3"
848     6'5"
860    5'11"
861     6'4"
862     6'1"
863     6'0"
864     6'1"
865    5'11"
866     6'2"
867     6'0"
868     6'3"
869     6'0"
871    5'10"
872     5'9"
873    5'11"
874     5'6"
875     6'1"
876     6'0"
877     6'4"
878     5'7"
879     6'0"
880    5'11"
881    5'11"
883     6'0"
884    5'10"
885     6'3"
886     6'0"
887     5'4"
888    5'11"
889     5'9"
890     5'7"
891     6'0"
892    5'10"
893     6'2"
894     6'2"
895     6'3"
896     5'7"
897    5'10"
898     5'9"
Name: Height, dtype: object

In [13]:
import re
def height_converter(height):
    match_ftich=re.match(r'(\d+)\'(\d+)\"', height)
    if match_ftich:
        feet=int(match_ftich.group(1))
        inches=int(match_ftich.group(2))
        total_inches=(feet*12)+inches
        cm=total_inches*2.54
        return int(cm)
    match_cm=re.match(r'(\d+)cm',height)
    if match_cm:
        return int(match_cm.group(1))
    return None

In [14]:
df['Height']=df['Height'].apply(height_converter)

In [15]:
df['Height'].head(10)

0    170
1    187
2    188
3    181
4    175
5    184
6    175
7    191
8    178
9    187
Name: Height, dtype: int64

In [16]:
df['Weight'].str.endswith('kg').all()

False

In [17]:
df['Weight'][~df['Weight'].str.endswith('kg')]

793    183lbs
847    179lbs
848    183lbs
860    172lbs
861    196lbs
862    176lbs
863    185lbs
864    179lbs
865    170lbs
866    196lbs
867    172lbs
868    203lbs
869    183lbs
871    168lbs
872    161lbs
873    146lbs
874    130lbs
875    190lbs
876    172lbs
877    174lbs
878    148lbs
879    165lbs
880    172lbs
881    161lbs
883    159lbs
884    170lbs
885    192lbs
886    181lbs
887    139lbs
888    154lbs
889    168lbs
890    170lbs
891    165lbs
892    157lbs
893    159lbs
894    181lbs
895    179lbs
896    148lbs
897    170lbs
898    163lbs
Name: Weight, dtype: object

In [18]:
def weight_converter(weight):
    match_lbs=re.match(r'(\d+)lbs', weight)
    if match_lbs:
        lbs=int(match_lbs.group(1))
        kg=lbs*0.453592
        return int(kg)
    match_kg=re.match(r'(\d+)kg',weight)
    if match_kg:
        return int(match_kg.group(1))
    return None

In [19]:
df['Weight']=df['Weight'].apply(weight_converter)
df['Weight'].head(10)

0    72
1    83
2    87
3    70
4    68
5    80
6    71
7    91
8    73
9    85
Name: Weight, dtype: int64

In [20]:
df.at[894,'Weight']

82

In [21]:
df.rename(columns={'Height':'Height(cm)'},inplace=True)
df.rename(columns={'Weight':'Weight(kg)'},inplace=True)
df.head()

,ID,Name,Nationality,Age,↓OVA,POT,Club,Contract,Positions,Height(cm),...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,158023,Lionel Messi,Argentina,33,93,93,\n\n\n\nFC Barcelona,2004 ~ 2021,"RW, ST, CF",170,...,Medium,Low,5 ★,85,92,91,95,38,65,771
1,20801,C. Ronaldo dos Santos Aveiro,Portugal,35,92,92,\n\n\n\nJuventus,2018 ~ 2022,"ST, LW",187,...,High,Low,5 ★,89,93,81,89,35,77,562
2,200389,Jan Oblak,Slovenia,27,91,93,\n\n\n\nAtlético Madrid,2014 ~ 2023,GK,188,...,Medium,Medium,3 ★,87,92,78,90,52,90,150
3,192985,Kevin De Bruyne,Belgium,29,91,91,\n\n\n\nManchester City,2015 ~ 2023,"CAM, CM",181,...,High,High,4 ★,76,86,93,88,64,78,207
4,190871,Neymar da Silva Santos Jr.,Brazil,28,91,91,\n\n\n\nParis Saint-Germain,2017 ~ 2022,"LW, CAM",175,...,High,Medium,5 ★,91,85,86,94,36,59,595

In [22]:
date_format= r'^[A-Za-z]{3} \d{1,2}, \d{4}$'
df['Joined'].str.match(date_format).all()

True

In [23]:
def club_cleaner(club):
    club=club.replace('\n','')
    return club

In [24]:
df['Club']=df['Club'].apply(club_cleaner)
df['Club'].head()

0           FC Barcelona
1               Juventus
2        Atlético Madrid
3        Manchester City
4    Paris Saint-Germain
Name: Club, dtype: object

In [25]:
salary_format=r'€\d+(\.\d+)?[MK]$'
df['Value'].str.match(salary_format).all()

False

In [26]:
df['Wage'].str.match(salary_format).all()

False

In [27]:
df['Release Clause'].str.match(salary_format).all()

False

In [28]:
df[['Value','Wage','Release Clause']][~df['Value'].str.match(salary_format)]

      Value Wage Release Clause
289      €0   €0             €0
292      €0   €0             €0
369      €0   €0             €0
374      €0   €0             €0
375      €0   €0             €0
...     ...  ...            ...
17220    €0   €0             €0
17343    €0   €0             €0
17659    €0   €0             €0
17661    €0   €0             €0
18205    €0   €0             €0

[248 rows x 3 columns]

In [29]:
df['Wage'].str.startswith('€').all()

True

In [30]:
def money_cleaner(col):
    col=col.replace('€','')
    return col

In [31]:
df['Wage']=df['Wage'].apply(money_cleaner)
df['Wage'].head()

0    560K
1    220K
2    125K
3    370K
4    270K
Name: Wage, dtype: object

In [32]:
df['Value']=df['Value'].apply(money_cleaner)

In [33]:
df['Release Clause']=df['Release Clause'].apply(money_cleaner)

In [34]:
df.rename(columns={'Value':'Value(€)'},inplace=True)
df.rename(columns={'Wage':'Wage(€)'},inplace=True)
df.rename(columns={'Release Clause':'Release Clause(€)'},inplace=True)
df.head(5)

,ID,Name,Nationality,Age,↓OVA,POT,Club,Contract,Positions,Height(cm),...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,158023,Lionel Messi,Argentina,33,93,93,FC Barcelona,2004 ~ 2021,"RW, ST, CF",170,...,Medium,Low,5 ★,85,92,91,95,38,65,771
1,20801,C. Ronaldo dos Santos Aveiro,Portugal,35,92,92,Juventus,2018 ~ 2022,"ST, LW",187,...,High,Low,5 ★,89,93,81,89,35,77,562
2,200389,Jan Oblak,Slovenia,27,91,93,Atlético Madrid,2014 ~ 2023,GK,188,...,Medium,Medium,3 ★,87,92,78,90,52,90,150
3,192985,Kevin De Bruyne,Belgium,29,91,91,Manchester City,2015 ~ 2023,"CAM, CM",181,...,High,High,4 ★,76,86,93,88,64,78,207
4,190871,Neymar da Silva Santos Jr.,Brazil,28,91,91,Paris Saint-Germain,2017 ~ 2022,"LW, CAM",175,...,High,Medium,5 ★,91,85,86,94,36,59,595

In [35]:
star_check=r'^\d+ ★$'
df['W/F'].str.match(star_check).all()

True

In [36]:
df['IR'].str.match(star_check).all()

True

In [37]:
star_check_1=r'^\d+★$'
df['SM'].str.match(star_check_1).all()

True

In [38]:
def star_space_remover(col):
    col=col.replace('★','')
    col=col.replace(' ','')
    return col

In [39]:
df['W/F']=df['W/F'].apply(star_space_remover)
df['W/F'].head()

0    4
1    4
2    3
3    5
4    5
Name: W/F, dtype: object

In [40]:
df['IR']=df['IR'].apply(star_space_remover)
df['IR'].head()

0    5
1    5
2    3
3    4
4    5
Name: IR, dtype: object

In [41]:
df['SM']=df['SM'].apply(star_space_remover)
df['SM'].head()

0    4
1    5
2    1
3    4
4    5
Name: SM, dtype: object

In [42]:
df.rename(columns={'W/F':'W/F(★)'},inplace=True)
df.rename(columns={'IR':'IR(★)'},inplace=True)
df.rename(columns={'SM':'SM(★)'},inplace=True)
df.head(5)

,ID,Name,Nationality,Age,↓OVA,POT,Club,Contract,Positions,Height(cm),...,A/W,D/W,IR(★),PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,158023,Lionel Messi,Argentina,33,93,93,FC Barcelona,2004 ~ 2021,"RW, ST, CF",170,...,Medium,Low,5,85,92,91,95,38,65,771
1,20801,C. Ronaldo dos Santos Aveiro,Portugal,35,92,92,Juventus,2018 ~ 2022,"ST, LW",187,...,High,Low,5,89,93,81,89,35,77,562
2,200389,Jan Oblak,Slovenia,27,91,93,Atlético Madrid,2014 ~ 2023,GK,188,...,Medium,Medium,3,87,92,78,90,52,90,150
3,192985,Kevin De Bruyne,Belgium,29,91,91,Manchester City,2015 ~ 2023,"CAM, CM",181,...,High,High,4,76,86,93,88,64,78,207
4,190871,Neymar da Silva Santos Jr.,Brazil,28,91,91,Paris Saint-Germain,2017 ~ 2022,"LW, CAM",175,...,High,Medium,5,91,85,86,94,36,59,595

In [43]:
count=df.apply(lambda row: row['Best Position'] in row['Positions'],axis=1).value_counts()
print('In position col: ',count[True])
print('Not in position col: ',count[False])

In position col:  15736
Not in position col:  3243

In [44]:
notin_position=df[~df.apply(lambda row: row['Best Position'] in row['Positions'],axis=1)]
notin_position=notin_position[['Positions','Best Position']]
notin_position

        Positions Best Position
68         LM, ST            RM
99        CDM, CM            CB
103        LW, RW           CAM
108            LB           LWB
111    LM, LB, CM           CAM
...           ...           ...
18969          CM            RM
18973          ST           CAM
18975          CM           CAM
18976          CM           CAM
18977          RW            ST

[3243 rows x 2 columns]

In [45]:
contract_format=r'\d{4} ~ \d{4}$'
df['Contract'].str.match(contract_format).all()

False

In [46]:
df['Contract']

0        2004 ~ 2021
1        2018 ~ 2022
2        2014 ~ 2023
3        2015 ~ 2023
4        2017 ~ 2022
            ...
18974    2018 ~ 2022
18975    2020 ~ 2021
18976    2019 ~ 2020
18977    2020 ~ 2022
18978    2019 ~ 2023
Name: Contract, Length: 18979, dtype: object

In [47]:
df['Contract'][~df['Contract'].str.match(contract_format)]

205      Jun 30, 2021 On Loan
248      Jun 30, 2021 On Loan
254      Jun 30, 2021 On Loan
289                      Free
292                      Free
                 ...
18472    Aug 31, 2021 On Loan
18571    Jun 30, 2021 On Loan
18600    Dec 31, 2020 On Loan
18622    Dec 31, 2020 On Loan
18680    Dec 31, 2020 On Loan
Name: Contract, Length: 1250, dtype: object

In [48]:
free_agent=df[df['Contract']=='Free']
'No Club' in free_agent['Club'].values

True

In [49]:
free_agent.head()

,ID,Name,Nationality,Age,↓OVA,POT,Club,Contract,Positions,Height(cm),...,A/W,D/W,IR(★),PAC,SHO,PAS,DRI,DEF,PHY,Hits
289,230347,Welington Kauê Dano Nascimento,Brazil,20,81,81,No Club,Free,"LB, LM",178,...,Medium,Medium,1,79,54,76,78,75,74,172
292,230225,Juan Everton Mestres de Mesquita,Brazil,24,81,81,No Club,Free,"CB, CDM",181,...,High,Medium,1,71,61,57,62,82,80,75
369,245299,Jaime Nicolás Frendado,Uruguay,36,80,80,No Club,Free,"CB, CDM",181,...,High,Medium,1,71,61,57,62,82,75,11
374,245294,Jorge Ezequiel Serendero,Uruguay,32,80,80,No Club,Free,GK,190,...,Medium,Medium,1,78,81,77,77,42,80,18
375,245308,Mauro Evidio Nérez,Uruguay,32,80,80,No Club,Free,"LB, LM",178,...,Medium,Medium,1,79,54,75,78,76,74,17

In [50]:
On_team_player=df.copy()

In [51]:
On_team_player=On_team_player[On_team_player['Contract']!='Free']
On_team_player=On_team_player.reset_index(drop=True)
On_team_player['Contract'][~On_team_player['Contract'].str.match(contract_format)].head()

205    Jun 30, 2021 On Loan
248    Jun 30, 2021 On Loan
254    Jun 30, 2021 On Loan
300    Jun 30, 2021 On Loan
304    Jun 30, 2021 On Loan
Name: Contract, dtype: object

In [52]:
Loan_player=On_team_player[~On_team_player['Contract'].str.match(contract_format)]
Loan_player.head()

,ID,Name,Nationality,Age,↓OVA,POT,Club,Contract,Positions,Height(cm),...,A/W,D/W,IR(★),PAC,SHO,PAS,DRI,DEF,PHY,Hits
205,173731,Gareth Bale,Wales,30,83,83,Tottenham Hotspur,"Jun 30, 2021 On Loan",RW,185,...,Medium,Medium,4,88,84,82,80,58,73,282
248,193105,Alphonse Areola,France,27,82,86,Fulham,"Jun 30, 2021 On Loan",GK,195,...,Medium,Medium,2,85,79,80,84,55,78,94
254,200888,Danilo Luís Hélio Pereira,Portugal,28,82,82,Paris Saint-Germain,"Jun 30, 2021 On Loan","CDM, CM",188,...,Medium,High,3,66,63,72,73,80,85,285
300,216409,Matteo Politano,Italy,26,81,81,Napoli,"Jun 30, 2021 On Loan","RM, RW, ST",171,...,High,Medium,2,83,77,78,84,42,55,93
304,223959,Lucas Torreira,Uruguay,24,81,85,Atlético Madrid,"Jun 30, 2021 On Loan","CDM, CM",166,...,Medium,High,2,74,67,75,79,79,74,194

In [53]:
On_team_player=On_team_player[On_team_player['Contract'].str.match(contract_format)]
On_team_player['Contract'].str.match(contract_format).all()

True

In [54]:
df.to_csv(r'/Users/chungkaichou/PycharmProjects/pythonProject1/PortFolio/Cleaning_Preprocessing/after_cleaning.csv',index=False, header=True)
On_team_player.to_csv(r'/Users/chungkaichou/PycharmProjects/pythonProject1/PortFolio/Cleaning_Preprocessing/on_team_player.csv',index=False, header=True)
Loan_player.to_csv(r'/Users/chungkaichou/PycharmProjects/pythonProject1/PortFolio/Cleaning_Preprocessing/loan_player.csv',index=False, header=True)
free_agent.to_csv(r'/Users/chungkaichou/PycharmProjects/pythonProject1/PortFolio/Cleaning_Preprocessing/free_agent.csv',index=False, header=True)